export const CHARACTERS=[
{id:"adrian",name:"Adrian Cross",occupation:"Museum Security Specialist",age:34,profile:"Six years at Blackwood; authorized for restricted access and assigned to the east side during the gala.",motive:"Frustrated that repeated security concerns were ignored.",portrait:"adrian.svg"},
{id:"bea",name:"Beatrice “Bea” Monroe",occupation:"Art Historian",age:41,profile:"Visiting curator who has published on the Star of Alexandria and knows its provenance history.",motive:"Disputes the museum's ownership records.",portrait:"bea.svg"},
{id:"caleb",name:"Caleb Reed",occupation:"Museum Technician",age:29,profile:"Maintains exhibition systems and legitimately uses the Service Corridor.",motive:"Fears technical failures could cost him his job.",portrait:"caleb.svg"},
{id:"diana",name:"Diana Hart",occupation:"Investigative Journalist",age:37,profile:"Invited journalist investigating the museum's ownership records; carries recording equipment.",motive:"Believes the museum is hiding the Star's true ownership.",portrait:"diana.svg"},
{id:"elias",name:"Elias Grant",occupation:"Private Art Collector",age:52,profile:"Major donor who previously tried to purchase the Star and was rejected.",motive:"Wanted the Star badly enough to make a serious offer.",portrait:"elias.svg"},
{id:"fiona",name:"Fiona Park",occupation:"Museum Conservator",age:32,profile:"Conservator who examined the Star before exhibition and understands its handling requirements.",motive:"Opposes the conditions under which the Star is being displayed.",portrait:"fiona.svg"},
{id:"marcus",name:"Marcus Bell",occupation:"Event Coordinator",age:45,profile:"Organized the gala and knows the schedule and guest movements.",motive:"Under pressure after several event-management mistakes.",portrait:"marcus.svg"},
{id:"naomi",name:"Naomi Sinclair",occupation:"Gemstone Appraiser",age:39,profile:"Independent expert whose reputation is tied to the Star's authentication.",motive:"The Star's authenticity could make or break her professional reputation.",portrait:"naomi.svg"}];
export const NPC={id:"vale",name:"Dr. Evelyn Vale",occupation:"Museum Director",age:58,profile:"Director of Blackwood Museum for 12 years. She authorized the Star exhibition and coordinated security.",motive:"Protects the museum's reputation.",portrait:"vale.svg",location:"Library"};
export const LOCATIONS=["Grand Gallery","East Hall","Library","Ballroom","Service Corridor","Courtyard"];
export const EDGES={"Grand Gallery":["East Hall","Service Corridor"],"East Hall":["Grand Gallery","Ballroom","Service Corridor","Library"],"Library":["East Hall"],"Ballroom":["East Hall","Courtyard"],"Courtyard":["Ballroom"],"Service Corridor":["East Hall","Grand Gallery"]};
export function shortestMinutes(a,b){if(a===b)return 0;const q=[[a,0]],seen=new Set([a]);while(q.length){const n=q.shift(),room=n[0],d=n[1];for(const next of EDGES[room]||[]){if(next===b)return d+1;if(!seen.has(next)){seen.add(next);q.push([next,d+1]);}}}return 99;}