import express from "express";import http from "http";import crypto from "crypto";import {Server} from "socket.io";import {CHARACTERS} from "./game/characters.js";import {generateCase} from "./game/cases.js";import {scoreAccusations} from "./game/scoring.js";
const app=express(),server=http.createServer(app),io=new Server(server,{connectionStateRecovery:{maxDisconnectionDuration:120000,maxEnqueuedMessages:20}});app.use(express.static("public"));const PORT=process.env.PORT||3000,rooms=new Map();
function code(){return crypto.randomBytes(4).toString("hex").toUpperCase().slice(0,5)}function clean(n){return String(n||"Detective").replace(/[<>]/g,"").slice(0,24)||"Detective"}
function publicRoom(r){return {code:r.code,phase:r.phase,hostId:r.hostId,players:r.players.map(function(p){return {id:p.id,name:p.name,character:p.character,characterName:p.characterName,occupation:p.occupation,connected:p.connected,score:p.score}}),caseData:r.caseData&&{title:r.caseData.title,crime:r.caseData.crime,timeline:r.caseData.timeline,publicEvidence:r.caseData.publicEvidence,profiles:r.caseData.profiles},endsAt:r.endsAt}}
function send(r,p){const x=publicRoom(r);x.me={id:p.id,name:p.name,character:p.character,characterName:p.characterName,occupation:p.occupation,score:p.score,role:r.caseData&&r.caseData.roles[p.character]||null,privateClues:r.caseData&&r.caseData.clues[p.character]||[]};x.voted=!!r.votes[p.id];x.votesSubmitted=Object.keys(r.votes).length;x.voteCount=r.players.length;io.to(p.id).emit("state",x)}
function broadcast(r){r.players.forEach(function(p){send(r,p)})}function room(s){return rooms.get(s.data.room)}
function start(r){const pool=[...CHARACTERS].sort(function(){return Math.random()-.5}).slice(0,r.players.length);r.players.forEach(function(p,i){p.character=pool[i].id;p.characterName=pool[i].name;p.occupation=pool[i].occupation});r.caseData=generateCase(r.players.length);r.phase="BRIEFING";r.votes={};r.endsAt=Date.now()+45000;broadcast(r);r.timer=setTimeout(function(){begin(r)},45000)}
function begin(r){if(r.phase!=="BRIEFING")return;r.phase="INVESTIGATION";r.endsAt=Date.now()+720000;broadcast(r);r.timer=setTimeout(function(){finish(r)},720000)}
function finish(r){if(r.phase!=="INVESTIGATION")return;r.phase="REVEAL";r.endsAt=null;r.revealAt=Date.now();scoreAccusations(r);broadcast(r)}
io.on("connection",function(s){
s.on("create",function(d){const p={id:s.id,name:clean(d&&d.name),character:null,characterName:null,occupation:null,score:0,connected:true};const r={code:code(),hostId:s.id,phase:"LOBBY",players:[p],caseData:null,votes:{},endsAt:null};rooms.set(r.code,r);s.join(r.code);s.data.room=r.code;broadcast(r)});
s.on("join",function(d){const r=rooms.get(String(d&&d.code||"").toUpperCase());if(!r)return s.emit("errorMsg","Room not found.");if(r.phase!=="LOBBY")return s.emit("errorMsg","That case has already started.");if(r.players.length>=8)return s.emit("errorMsg","Room is full.");const p={id:s.id,name:clean(d&&d.name),character:null,characterName:null,occupation:null,score:0,connected:true};r.players.push(p);s.join(r.code);s.data.room=r.code;broadcast(r)});
s.on("start",function(){const r=room(s);if(r&&r.hostId===s.id&&r.players.length>=2&&r.phase==="LOBBY")start(r)});
s.on("beginInvestigation",function(){const r=room(s);if(r&&r.phase==="BRIEFING")begin(r)});
s.on("accuse",function(d){const r=room(s);if(!r||r.phase!=="INVESTIGATION"||r.votes[s.id])return;const target=r.players.find(function(p){return p.id===d.targetId});if(!target||target.id===s.id)return;r.votes[s.id]=target.character;if(Object.keys(r.votes).length===r.players.length)finish(r);else broadcast(r)});
s.on("rematch",function(){const r=room(s);if(!r||r.hostId!==s.id||r.phase!=="REVEAL")return;r.phase="LOBBY";r.caseData=null;r.votes={};r.endsAt=null;r.players.forEach(function(p){p.character=null;p.characterName=null;p.occupation=null;p.score=0});broadcast(r)});
s.on("disconnect",function(){const r=room(s);if(!r)return;const p=r.players.find(function(x){return x.id===s.id});if(p)p.connected=false;broadcast(r)});
});
setInterval(function(){for(const [k,r] of rooms){if(r.phase==="REVEAL"&&Date.now()-r.revealAt>1800000)rooms.delete(k)}},60000);
server.listen(PORT,function(){console.log("The Case of the Stolen Crown on "+PORT)});